import { useEffect, useMemo, useState } from "react";
import { api, type RetrospectiveEvaluation } from "../services/api";

export const evaluationCaveat = "This page compares selected Issue Triage evidence with independently recorded public maintenance history. It is a small curated sample, not an accuracy benchmark or a claim of autonomous triage correctness.";
function display(value: string | null) { return value ? value.replaceAll("_", " ") : "Unavailable"; }

export function RetrospectiveEvaluation() {
  const [data, setData] = useState<RetrospectiveEvaluation>();
  useEffect(() => { api.retrospectiveEvaluation().then(setData).catch(() => setData({ status: "invalid", reason: "Curated evaluation data is unavailable." })); }, []);
  const counts = useMemo(() => { const result: Record<string, number> = {}; data?.dataset?.cases.forEach((item) => { result[item.external_support] = (result[item.external_support] ?? 0) + 1; }); return result; }, [data]);
  const classifications = useMemo(() => { const result: Record<string, number> = {}; data?.dataset?.cases.forEach((item) => { const key = item.classification ?? "UNCLASSIFIED"; result[key] = (result[key] ?? 0) + 1; }); return result; }, [data]);
  if (!data) return <p role="status">Loading retrospective evidence review…</p>;
  if (data.status === "invalid") return <section className="empty-state"><p className="eyebrow">Retrospective evidence review</p><h1>Curated evaluation data is unavailable</h1><p>{data.reason}</p><a className="button-link" href="?results=1">Evidence Results</a></section>;
  if (data.status === "no_data" || !data.dataset?.cases.length) return <section className="empty-state"><p className="eyebrow">Retrospective evidence review</p><h1>No independently curated retrospective cases are available in this demo.</h1><p>Existing live investigation results remain available in Evidence Results.</p><div className="brief-actions"><a className="button-link" href="?results=1">Evidence Results</a><a className="button-link" href="?brief=1">Evidence Brief</a><a className="button-link" href="/">Triage Queue</a></div></section>;
  return <section className="evaluation-page"><p className="eyebrow">Independent historical context</p><h1>Retrospective evidence review</h1><p className="results-caveat">{evaluationCaveat}</p><p className="metadata">Dataset {data.dataset.schema_version} · {data.dataset.cases.length} included · {data.dataset.excluded_case_count} excluded · captured {data.dataset.captured_at ?? "date unavailable"}</p><section className="results-grid" aria-label="External support counts">{Object.entries(counts).map(([key, value]) => <article className="result-card" key={key}><strong>{value}</strong><span>{display(key)}</span></article>)}</section><section className="results-grid" aria-label="Issue Triage classification counts">{Object.entries(classifications).map(([key, value]) => <article className="result-card" key={key}><strong>{value}</strong><span>{display(key)}</span></article>)}</section><section className="card"><h2>Dataset limitations</h2><ul>{data.dataset.limitations?.map((item) => <li key={item}>{item}</li>)}</ul>{data.dataset.exclusion_rationale && <p>{data.dataset.exclusion_rationale}</p>}</section><section className="evaluation-cases">{data.dataset.cases.map((item) => <article className="card" key={item.case_id}><div className="section-heading"><div><p className="eyebrow">{item.external_support.replaceAll("_", " ")}</p><h2><a href={item.issue_url} target="_blank" rel="noreferrer">{item.repository} #{item.issue_number} ↗</a></h2></div>{item.investigation_id && <a className="button-link" href={`?id=${encodeURIComponent(item.investigation_id)}`}>Open local evidence</a>}</div><p>{item.title}</p><p><b>Historical record:</b> {item.historical_state}</p><p><b>Issue Triage conclusion:</b> {display(item.classification)} · {display(item.terminal_status)}</p><p><b>Validation:</b> {item.validation_reason ?? "Unavailable"}</p><p><b>External support:</b> {item.evaluator_note}</p><p><b>Limitations:</b> {item.limitations}</p><p className="evaluation-sources">{item.sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.source_type.replaceAll("_", " ")}: {source.title}</a>)}</p><p className="metadata">Tracked OpenAI cost: {item.tracked_openai_cost ?? "Unavailable"} · latency: {item.tracked_openai_latency ?? "Unavailable"} · Codex wall time: {item.codex_wall_time ?? "Unavailable"}</p></article>)}</section></section>;
}
