import { useEffect, useMemo, useState } from "react";
import { SemanticEvidenceView } from "../components/SemanticReviewCard";
import { api, type AssessmentInput, type PilotPacket, type ReviewOutcome } from "../services/api";

const questions = [["extraction_aligned", "Does the extraction represent the bounded behavior claim?"], ["test_aligned", "Does the generated test represent that claim?"], ["failure_supports_signal", "Does the structured failure support the claimed signal?"], ["public_comment_appropriate", "Would a public comment be appropriate?"]] as const;
const initial: AssessmentInput = { extraction_aligned: "YES", test_aligned: "YES", failure_supports_signal: "YES", public_comment_appropriate: "YES", confidence: "MEDIUM", rationale: "" };
function derived(values: AssessmentInput): ReviewOutcome { const answers = [values.extraction_aligned, values.test_aligned, values.failure_supports_signal, values.public_comment_appropriate]; return answers.includes("NO") ? "MISALIGNED" : answers.some((value) => value === "UNCERTAIN" || value === "NOT_ENOUGH_CONTEXT") ? "UNCLEAR" : "ALIGNED"; }

export function ReviewerPacket({ packetId }: { packetId: string }) {
  const [packet, setPacket] = useState<PilotPacket>(); const [values, setValues] = useState<AssessmentInput>(initial); const [error, setError] = useState<string>(); const [submitted, setSubmitted] = useState<ReviewOutcome>();
  useEffect(() => { api.pilotPacket(packetId).then((result) => setPacket(result.packet)).catch((err: Error) => setError(err.message)); }, [packetId]);
  const outcome = useMemo(() => derived(values), [values]);
  if (error) return <section><a className="back-link" href="/?reviewer=1">← Reviewer queue</a><p className="error">Unable to load review packet: {error}</p></section>;
  if (!packet) return <section><p role="status">Loading immutable review packet…</p></section>;
  return <section><a className="back-link" href="/?reviewer=1">← Reviewer queue</a><div className="page-heading"><div><p className="eyebrow">Authenticated semantic-fidelity review</p><h1>{packet.repository} #{packet.issue_number}</h1><p>{packet.issue_title ?? "Issue title not retained"}</p></div><span className="badge">{packet.display_state}</span></div><p className="metadata">{packet.coverage.MAINTAINER ?? 0} maintainer / {packet.coverage.INDEPENDENT_ENGINEER ?? 0} independent engineers. This review never changes deterministic validation or classification.</p><SemanticEvidenceView review={{ packet_version: packet.version, evidence: packet.evidence, state: packet.state, display_state: packet.display_state, coverage: packet.coverage }} /><section className="card"><h2>Reviewer decision</h2><p className="metadata">Derived review outcome: <b>{outcome}</b>. It is derived only from the four required judgments; confidence does not override it.</p><form className="assessment-form" onSubmit={(event) => { event.preventDefault(); setError(undefined); api.submitAssessment(packet.id, values).then((result) => setSubmitted(result.derived_review_outcome)).catch((err: Error) => setError(err.message)); }}>{questions.map(([key, label]) => <label key={key}>{label}<select value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })}>{["YES", "NO", "UNCERTAIN", "NOT_ENOUGH_CONTEXT"].map((value) => <option key={value}>{value}</option>)}</select></label>)}<label>Confidence<select value={values.confidence} onChange={(event) => setValues({ ...values, confidence: event.target.value })}>{["LOW", "MEDIUM", "HIGH"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Rationale {outcome !== "ALIGNED" ? "(required)" : "(optional)"}<textarea value={values.rationale} maxLength={4000} required={outcome !== "ALIGNED"} onChange={(event) => setValues({ ...values, rationale: event.target.value })} /></label><button type="submit">Submit append-only assessment</button></form>{submitted && <p role="status">Assessment recorded with derived outcome: {submitted}.</p>}{error && <p className="error">{error}</p>}</section></section>;
}
