import { useEffect, useState } from "react";
import { api, type PilotUser, type ReviewQueueItem } from "../services/api";

export function ReviewerQueue() {
  const [user, setUser] = useState<PilotUser>(); const [items, setItems] = useState<ReviewQueueItem[]>([]); const [error, setError] = useState<string>(); const [reviewerId, setReviewerId] = useState(""); const [token, setToken] = useState("");
  const load = () => api.reviewQueue().then((result) => setItems(result.items)).catch((err: Error) => setError(err.message));
  useEffect(() => { api.pilotMe().then((item) => { setUser(item); load(); }).catch(() => undefined); }, []);
  if (!user) return <section className="card"><p className="eyebrow">Internal pilot reviewer tool</p><h1>Reviewer sign in</h1><p>This local/internal pilot uses a secure cookie; your reviewer token is exchanged once and is not stored in the browser.</p><form onSubmit={(event) => { event.preventDefault(); setError(undefined); api.pilotLogin(reviewerId, token).then((item) => { setToken(""); setUser(item); load(); }).catch((err: Error) => setError(err.message)); }}><label>Reviewer ID<input required value={reviewerId} onChange={(event) => setReviewerId(event.target.value)} /></label><label>Reviewer token<input required type="password" value={token} onChange={(event) => setToken(event.target.value)} /></label><button type="submit">Sign in</button></form>{error && <p className="error">{error}</p>}</section>;
  return <section><div className="page-heading"><div><p className="eyebrow">Authenticated internal pilot</p><h1>Reviewer queue</h1><p>{user.reviewer.external_id} · {user.reviewer.cohort}</p></div><div><a className="button-link" href="/?reviewer=1&reports=1">Weekly reports</a> <button onClick={() => api.pilotLogout().then(() => { setUser(undefined); setItems([]); })}>Sign out</button></div></div><p className="metadata">Semantic review is separate from deterministic test validation and does not change the investigation verdict.</p>{error ? <p className="error">Unable to load review queue: {error}</p> : items.length === 0 ? <p role="status">No cases currently require reviewer attention.</p> : <table className="investigation-table"><thead><tr><th>Issue</th><th>Verdict</th><th>Semantic review</th><th>Coverage</th><th>Comment</th><th>Age</th></tr></thead><tbody>{items.map((item) => <tr key={item.packet_id}><td><a href={`/?id=${item.investigation_id}`}>{item.repository} #{item.issue_number}</a><small>{item.issue_title}</small></td><td>{item.classification}<small>assertsFailure: {String(item.asserts_failure)}</small></td><td>{item.consensus_state}</td><td>{item.coverage.MAINTAINER ?? 0} maintainer / {item.coverage.INDEPENDENT_ENGINEER ?? 0} of 2 independent</td><td>{item.comment_status ?? item.posting_eligibility}</td><td>{item.review_age_started_at ? new Date(item.review_age_started_at).toLocaleDateString() : "—"}</td></tr>)}</tbody></table>}</section>;
}
