import type { Investigation } from "../services/api";
import { CopyButton } from "./CopyButton";
import { formatDate, formatDuration, formatUsd } from "./format";
import { StatusBadge } from "./StatusBadge";
import { ValidationHelp } from "./ValidationHelp";

export function InvestigationTable({ items, filtered = false }: { items: Investigation[]; filtered?: boolean }) {
  if (!items.length) return <div className="empty-state"><strong>{filtered ? "No investigations match this repository." : "No investigations have been run yet."}</strong><br /><br />{filtered ? "Choose another repository to see more evidence." : <>Run: <code>triage investigate &lt;issue_number&gt;</code> to create your first investigation.</>}</div>;
  return <div className="table-wrap"><table><thead><tr><th scope="col">Issue</th><th scope="col">Verdict</th><th scope="col"><span className="header-with-help">assertsFailure <ValidationHelp kind="assertsFailure" /></span></th><th scope="col">Confidence</th><th scope="col">Tracked API cost</th><th scope="col">API latency</th><th scope="col">Completed</th><th scope="col">Duration</th><th scope="col" aria-label="Open" /></tr></thead><tbody>
    {items.map((item) => { const href = `?id=${encodeURIComponent(item.id)}`; const title = item.issue_title ?? "Issue title not retained"; const metric = item.tracked_llm_api_cost_usd === null ? <span className="unavailable" title={item.tracked_llm_api_explanation}>—</span> : formatUsd(item.tracked_llm_api_cost_usd); const latency = item.tracked_llm_api_latency_ms === null ? <span className="unavailable" title={item.tracked_llm_api_explanation}>—</span> : `${(item.tracked_llm_api_latency_ms / 1000).toFixed(1)}s`; return <tr key={item.id} className="investigation-row"><td><a className="investigation-link" href={href}><strong>{item.repository} <span aria-hidden="true">#</span>{item.issue_number}</strong><span className="issue-title" title={title}>{title}</span><span className="run-id"><code>{item.id.slice(0, 8)}</code></span></a><CopyButton value={item.id} label="Copy investigation ID" /></td><td><a href={href} aria-label={`Open ${item.repository} issue ${item.issue_number}`}><StatusBadge value={item.classification} /></a></td><td><a href={href} aria-label={`Open ${item.repository} issue ${item.issue_number}`}><StatusBadge value={item.asserts_failure} /></a></td><td><span className="unavailable" title="Extraction confidence is not persisted as investigation confidence.">—</span></td><td>{metric}</td><td>{latency}</td><td><a href={href} aria-label={`Open ${item.repository} issue ${item.issue_number}`}>{formatDate(item.completed_at ?? item.updated_at)}</a></td><td><a href={href} aria-label={`Open ${item.repository} issue ${item.issue_number}`}>{formatDuration(item.duration_seconds)}</a></td><td><a className="row-chevron" href={href} aria-label={`Open ${item.repository} issue ${item.issue_number}`}>›</a></td></tr>; })}
  </tbody></table></div>;
}
