import type { SemanticReview } from "../services/api";

function Evidence({ review }: { review: NonNullable<SemanticReview["review"]> }) {
  const { claim, generated_test, junit, validation_reason } = review.evidence;
  return <div className="semantic-evidence"><section><h3>Bounded behavior claim</h3>{claim.available ? <><p>{claim.summary ?? "No extraction summary retained."}</p><dl><dt>Expected</dt><dd>{claim.expected_behavior ?? "—"}</dd><dt>Actual</dt><dd>{claim.actual_behavior ?? "—"}</dd></dl>{claim.missing_information?.length ? <p className="metadata">Missing information: {claim.missing_information.join("; ")}</p> : null}</> : <p className="metadata">No bounded extraction was retained.</p>}</section><section><h3>Generated test claim</h3><p>{generated_test.hypothesis ?? "No persisted attempt hypothesis is available."}</p>{generated_test.changed_test_paths?.length ? <p className="metadata">Changed test path: {generated_test.changed_test_paths.join(", ")}</p> : null}</section><section><h3>Assertion evidence</h3>{generated_test.available ? <>{generated_test.assertion_lines?.length ? <pre className="semantic-code">{generated_test.assertion_lines.join("\n")}</pre> : <p className="metadata">No assertion-like changed line was found. This does not establish misalignment.</p>}{generated_test.diff_excerpt && <details><summary>View bounded diff excerpt</summary><pre className="semantic-code">{generated_test.diff_excerpt}</pre></details>}</> : <p className="metadata">{generated_test.reason}</p>}</section><section><h3>Structured JUnit failure</h3>{junit.available ? <><p><code>{junit.testcase}</code></p><pre className="semantic-code">{junit.failure ?? "Failure text was not retained."}</pre></> : <p className="metadata">{junit.reason}</p>}{validation_reason ? <p className="metadata">Deterministic validation: {validation_reason}</p> : null}</section></div>;
}

export function SemanticReviewCard({ data, loading }: { data?: SemanticReview; loading: boolean }) {
  if (loading) return <section className="card" aria-busy="true"><h2>Semantic fidelity review</h2><p>Loading review provenance…</p></section>;
  if (!data || data.packet_status !== "AVAILABLE" || !data.review) return <section className="card"><h2>Semantic fidelity review</h2><p><b>{data?.packet_status === "UNAVAILABLE" ? "Unavailable" : "Not issued"}</b> — {data?.reason ?? "Review provenance is unavailable."}</p><p className="metadata">Semantic review does not change deterministic validation or the investigation classification.</p></section>;
  const { review } = data;
  return <section className="card semantic-review" id="semantic-review"><div className="section-heading"><div><p className="eyebrow">Human semantic review</p><h2>Semantic fidelity review</h2></div><span className="badge">{review.display_state}</span></div><p className="metadata">Review packet v{review.packet_version} · {review.coverage.MAINTAINER ?? 0} maintainer / {review.coverage.INDEPENDENT_ENGINEER ?? 0} independent engineers</p><Evidence review={review} /><p className="semantic-boundary">Semantic review does not change deterministic validation or the investigation classification.</p></section>;
}

export { Evidence as SemanticEvidenceView };
