from enum import StrEnum


class InvestigationStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    # The bounded investigation completed normally but did not establish a
    # clean behavior gap. Its classification carries the outcome; this status
    # distinguishes it from setup/runtime/budget failures.
    COMPLETED_NO_GAP = "COMPLETED_NO_GAP"
    FAILED = "FAILED"


class Classification(StrEnum):
    BEHAVIOR_GAP_CONFIRMED = "BEHAVIOR_GAP_CONFIRMED"
    NEEDS_INFO = "NEEDS_INFO"
    WONT_REPRO = "WONT_REPRO"
    NOT_A_BUG = "NOT_A_BUG"
    DUPLICATE = "DUPLICATE"


class WebhookJobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    # Retained for existing persisted task-1 records; new workers use SUCCEEDED.
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    CANCELLED = "CANCELLED"
    DEAD_LETTER = "DEAD_LETTER"


class JobSource(StrEnum):
    WEBHOOK = "WEBHOOK"
    BATCH = "BATCH"
    MANUAL = "MANUAL"
    LIVE_DEMO = "LIVE_DEMO"


class CommentStatus(StrEnum):
    PENDING = "PENDING"
    PROPOSED = "PROPOSED"
    POSTED = "POSTED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    CONSENSUS_REQUIRED = "CONSENSUS_REQUIRED"


class BudgetStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    EXCEEDED = "EXCEEDED"
    UNBUDGETABLE = "UNBUDGETABLE"


class ReviewerCohort(StrEnum):
    MAINTAINER = "MAINTAINER"
    INDEPENDENT_ENGINEER = "INDEPENDENT_ENGINEER"


class AssessmentJudgment(StrEnum):
    YES = "YES"
    NO = "NO"
    UNCERTAIN = "UNCERTAIN"
    NOT_ENOUGH_CONTEXT = "NOT_ENOUGH_CONTEXT"


class AssessmentConfidence(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ConsensusState(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    UNANIMOUSLY_ALIGNED = "UNANIMOUSLY_ALIGNED"
    DISAGREED = "DISAGREED"
    REJECTED_ALIGNMENT = "REJECTED_ALIGNMENT"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"
    UNAVAILABLE = "UNAVAILABLE"


class PostingApprovalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONSUMED = "CONSUMED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class ReviewActivityType(StrEnum):
    QUEUE_OPENED = "QUEUE_OPENED"
    PACKET_OPENED = "PACKET_OPENED"
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_RESUMED = "REVIEW_RESUMED"
    HEARTBEAT = "HEARTBEAT"
    ASSESSMENT_SUBMITTED = "ASSESSMENT_SUBMITTED"
    ASSESSMENT_SUPERSEDED = "ASSESSMENT_SUPERSEDED"
    POSTING_APPROVAL_CREATED = "POSTING_APPROVAL_CREATED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    REVIEW_ABANDONED = "REVIEW_ABANDONED"


class CorpusConsentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"


class EligibilityState(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    INSUFFICIENT_COVERAGE = "INSUFFICIENT_COVERAGE"
    FALSE_ALIGNMENT_DETECTED = "FALSE_ALIGNMENT_DETECTED"
    DISAGREEMENT_PRESENT = "DISAGREEMENT_PRESENT"
    PRECISION_BELOW_THRESHOLD = "PRECISION_BELOW_THRESHOLD"
    DATA_QUALITY_BLOCKED = "DATA_QUALITY_BLOCKED"
    MEASUREMENT_ELIGIBLE = "MEASUREMENT_ELIGIBLE"
